### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by qxl1231** [hashrock-sandbox/study-loopback-vue#1]
how to use this loopback+vue? when i start node .  it makes a lot of error:

Error: Cannot GET /bundle.js
    at raiseUrlNotFoundError (/Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request](/Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/express/lib/router/index.js:312:13)
    at /Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/serve-static/index.js:120:7)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (/Users/Ivyjohnson/WebstormProjects/study-loopback-vue/node_modules/send/index.js:245:17)

**Comment by hashrock** [comment]
Please run this after `npm install`

```
 $ npm run build:js
```

**Comment by qxl1231** [comment]
thank you, how to make this project hot reload ? i use node . cant hot reload...Q.Q

**Comment by hashrock** [comment]
To use hot reload, please try this command:

```
 $ npm run watch:js & node .
```

If you have error, try this: 

```
npm install\
  vueify-insert-css vue-hot-reload-api\
  babel-core babel-preset-es2015\
  babel-plugin-transform-runtime babel-runtime@5\
  --save-dev
```

Hot reloading detail: 
https://github.com/vuejs/vueify

**Comment by qxl1231** [comment]
thank you very much. can i have your wechat or qq,or facebook,or any online chat ID? i make a new model, but i cant work wrightly  ..sadness

**Comment by hashrock** [comment]
If you are new to loopback, I think this repository is not good start point for you.
This repository is just an exercise for myself and there are not any documents.

If you are getting trouble with loopback model, I recommend you to read [Loopback tutorial](https://docs.strongloop.com/display/public/LB/Getting+started+with+LoopBack) first.
It's difficult for me to guess your problems because I'm not a loopback expert.

I'm not using any chat service, but please feel free to comment here.

**Comment by qxl1231** [comment]
<style>
    html, body {
        margin: 0;
        padding: 0;
        height: 100vh;
    }

    main {
        display: flex;
        height: 100%;
    }

    .browser__list {
        width: 150px;
        background: #666;
    }

    textarea {
        flex: 1;
        background: #333;
        color: white;
    }

    .preview {
        flex: 1;
    }

    .browser__list__new {
        width: 100%;
        margin: 0;
        height: 2rem;
    }
</style>


<template>
    <main>
        <aside class="browser__list">
            <button class="browser__list__new" @click="addApp">New</button>
            <browser-item v-for="app in apps" :post="app" @click="selectApp(app)"
                          :editing-id="editing.id"></browser-item>
        </aside>
        <textarea v-model="editing.name" @keyup="updateApp | debounce 500"></textarea>

        <div class="preview" v-text="editing.name"></div>
    </main>
</template>

<script>
    var apps;

    module.exports = {
        http: {
            root: '/api'
        },
        events: {
            "remove-app": function (app) {
                var self = this;
                if (confirm(app.name + "确定删除？")) {
                    apps.delete({id: app.id}, function (data, status, request) {
                        self.fetchApps();
                    });
                }
            }
        },
        data: function () {
            return {
                msg: 'Replaceing',
                apps: [],
                editing: {
                    id: "",
                    name: "apptest"
                }
            }
        },
        methods: {
            addApp: function () {
                var self = this;
                var id = window.prompt("id:");
                var name = window.prompt("name:");

                if(id&&name){
                    apps.save({}, {id: id,name: name}, function(data, status, request){
                        self.editing = data;
                        self.fetchApps();
                    });
                }

            },
            updateApp: function () {
                if (this.editing.id || this.editing.id.length > 0) {
                    apps.update({id: this.editing.id}, this.editing, function (data, status, request) {
                        console.log("saved");
                    })
                }
            },
            selectApp: function (app) {
                this.editing = app;

            },
            fetchApps: function () {
                var self = this;
                apps.query({}, function (items, status, request) {
                    self.apps = items;
                })
            }
        },
        ready: function () {
            apps = this.$resource('apps/:id');
            this.fetchApps();
        },
        components: {
            browserItem: require("./browser-item2.vue")
        }


    }
</script>

===============
<template>
	<div class="browser__item" :class="{'editing': app.id === editingId}">
		{{app.id}}
		<div class="browser__item__delete" @click="remove">
			x
		</div>
	</div>
</template>

<script>
	module.exports = {
		props: ["app", "editingId"],
		data: function(){
			return {
			}
		},
		methods: {
			remove: function(){
				this.$dispatch("remove-app", this.app);
			}
		}
	}
	
</script>



this code cant work like yours, loopback i know well,but not real understand vue and vue-resource.so i need your help ..^.^

**Comment by qxl1231** [comment]
{
  "name": "app",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "required": true
    },
    "name": {
      "type": "string",
      "required": true
    },
    "createTime": {
      "type": "date"
    },
    "updateTime": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {
    "versions": {
      "type": "hasMany",
      "model": "version",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}


this is the model define of app

**Comment by qxl1231** [comment]
thank you very much, i m a backend developer. and skilled at loopback,but new in vue and vue related ,im learning front end

**Comment by hashrock** [comment]
Keep it up! :+1:
